PROTOCOL: str = "http"
API_HOST_URL: str = "127.0.0.1"
CORE_API_PORT: int = 4710
IP_API_PORT: int = 4711

CORE_API_BASE_URL: str = f"{PROTOCOL}://{API_HOST_URL}:{CORE_API_PORT}"
IP_API_BASE_URL: str = f"{PROTOCOL}://{API_HOST_URL}:{IP_API_PORT}"
