[project]
name = "image"
version = "0.0.1"
description = ""
# authors = []
requires-python = ">=3.11"

[tool.poetry.dependencies]
tflite-runtime = "^2.14.0"
opencv-python = "<4.10"
picamera2 = "^0.3.31"
numpy = "<2"
